version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      BASE_URL: ${BASE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      JWT_SECRET: ${JWT_SECRET}
      EXPIRED_IN: ${EXPIRED_IN}
      LOG_LEVEL: ${LOG_LEVEL}
    depends_on:
      - db
    networks:
      - app_network
    command: >
      sh -c "
             npm install npm@10.8.2 &&
             npm install sequelize-cli &&
             yarn sequelize db:migrate &&
             yarn sequelize db:seed:all &&
             node server.js"


volumes:
  db_data:
    driver: local

networks:
  app_network:
    driver: bridge
